name: Build and Push Docker Image on Change in code

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: arthurem/url_shortener:latest

      # - name: Build & push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: arthurem/url_shortener_docker
      #     tags: v1, latest
      #     registry: docker.io
      #     # dockerfile: Dockerfile.ci
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
